export const packageName = '@dongtian/contracts' as const;

export { openApiDocument } from './generated/openapi.js';
export type { OpenApiDocument } from './generated/openapi.js';
export {
  ApiClientError,
  createApiClient,
  type ApiClient,
  type ApiClientOptions,
  type ApiEnvelope,
  type ActionCatalogEntry,
  type CharacterProgression,
  type DungeonChoiceRequest,
  type DungeonOpportunityDetails,
  type DungeonOpportunityCharacter,
  type DungeonOpportunityResponse,
  type DungeonPreviewChoice,
  type DungeonPreviewEntry,
  type DungeonPreviewRequest,
  type DungeonPreviewResponse,
  type DungeonRunCreateRequest,
  type DungeonRunDetails,
  type DungeonRunResponse,
  type DungeonTeachingGrantDetails,
  type ContentActionsResponse,
  type ContentCharacterSummary,
  type ContentItemQuantity,
  type ContentRecipesResponse,
  type ContentRoute,
  type ContentUnlockState,
  type AuthAccountStatus,
  type AuthAccountType,
  type AuthActiveSession,
  type AuthAnonymousSession,
  type AuthLogout,
  type EquipmentInstance,
  type EquipmentSlot,
  type FeaturePermission,
  type InventoryAsset,
  type InventorySnapshot,
  type AuthSession,
  type LoadoutConsumable,
  type LoadoutPreset,
  type LoadoutPresetSaveRequest,
  type Manifest,
  type Queue,
  type QueueBlockedPolicy,
  type QueueEntry,
  type QueueEntryStatus,
  type QueueMutation,
  type QueueMode,
  type QueuePlanEntry,
  type QueuePlanFallback,
  type QueuePlanRequest,
  type QueuePreview,
  type QueuePreviewEntry,
  type QueuePreviewWarning,
  type QueueVersionRequest,
  type RecipeCatalogEntry,
  type LatestSettlementResponse,
  type LatestSettlementSummary,
  type SettlementJson,
  type SettlementLedgerEntry,
  type SettlementRewardItem,
  type SettlementRewards,
  type SettlementTimelineEntry,
  type SkillProgression,
} from './web-client.js';
