// Generated by scripts/generate-game-config.mjs. Do not edit manually.
export const PARAMETER_MANIFEST = { version: '1.0.0-frozen', sha256: '7113fe72dd40ed36869408551f5f20a9e72e83af519b4a03d657296ed4987f75', rows: 1143, source: 'docs/洞天数值参数表.csv' } as const;
