// Generated by scripts/generate-game-config.mjs. Do not edit manually.
export const PARAMETER_MANIFEST = { version: '1.0.0-frozen', sha256: 'f67401fefb406a32b2e58abaabb655c12d56dbfe33309278a3780b9f82565a63', rows: 1156, source: 'docs/洞天数值参数表.csv' } as const;
