// Generated by scripts/generate-game-config.mjs. Do not edit manually.
export const PARAMETER_MANIFEST = { version: '1.0.0-frozen', sha256: '944c1655e47999bc4405239836b2398749b169d21d61a1f32e20e88bb20f8c92', rows: 1143, source: 'docs/洞天数值参数表.csv' } as const;
